import { MatchCardData } from "@/lib/db/types";

export const SAMPLE_MATCH_CARD_DATA: MatchCardData[] = [
  {
    team: 118,
    matches: 12,
    avgShootingSeconds: 4.8,
    maxShootingSeconds: 7.1,
    avgFeedingSeconds: 3.2,
    trench: true,
    bump: false,
    halfFieldFromNeutral: true,
    halfFieldFromOpponent: false,
    fullField: true,
    L3Climbs: 6,
    L2Climbs: 4,
    L1Climbs: 2,
    autoClimbs: 3,
    avgAutoShootingSeconds: 2.9,
    maxAutoShootingSeconds: 4.6,
    avgAutoFeedingSeconds: 1.4,
    avgAutoAttemptedSeconds: 3.1,
    autoShootingAccuracy: 0.72,
    avgTeleopShootingSeconds: 5.2,
    maxTeleopShootingSeconds: 7.8,
    teleopShootingAccuracy: 0.64,
    autoTrench: true,
    autoBump: false,
    autoFeed: true,
  },
  {
    team: 1678,
    matches: 11,
    avgShootingSeconds: 5.1,
    maxShootingSeconds: 7.4,
    avgFeedingSeconds: 3.6,
    trench: true,
    bump: true,
    halfFieldFromNeutral: true,
    halfFieldFromOpponent: true,
    fullField: false,
    L3Climbs: 5,
    L2Climbs: 5,
    L1Climbs: 1,
    autoClimbs: 4,
    avgAutoShootingSeconds: 3.2,
    maxAutoShootingSeconds: 4.8,
    avgAutoFeedingSeconds: 1.7,
    avgAutoAttemptedSeconds: 3.4,
    autoShootingAccuracy: 0.68,
    avgTeleopShootingSeconds: 5.6,
    maxTeleopShootingSeconds: 8.0,
    teleopShootingAccuracy: 0.61,
    autoTrench: true,
    autoBump: true,
    autoFeed: false,
  },
  {
    team: 254,
    matches: 10,
    avgShootingSeconds: 4.4,
    maxShootingSeconds: 6.9,
    avgFeedingSeconds: 2.8,
    trench: false,
    bump: true,
    halfFieldFromNeutral: true,
    halfFieldFromOpponent: false,
    fullField: false,
    L3Climbs: 4,
    L2Climbs: 3,
    L1Climbs: 3,
    autoClimbs: 2,
    avgAutoShootingSeconds: 2.5,
    maxAutoShootingSeconds: 3.9,
    avgAutoFeedingSeconds: 1.1,
    avgAutoAttemptedSeconds: 2.6,
    autoShootingAccuracy: 0.66,
    avgTeleopShootingSeconds: 4.9,
    maxTeleopShootingSeconds: 7.0,
    teleopShootingAccuracy: 0.58,
    autoTrench: false,
    autoBump: true,
    autoFeed: true,
  },
  {
    team: 441,
    matches: 9,
    avgShootingSeconds: 5.7,
    maxShootingSeconds: 8.2,
    avgFeedingSeconds: 3.9,
    trench: true,
    bump: false,
    halfFieldFromNeutral: false,
    halfFieldFromOpponent: true,
    fullField: true,
    L3Climbs: 3,
    L2Climbs: 4,
    L1Climbs: 2,
    autoClimbs: 3,
    avgAutoShootingSeconds: 3.6,
    maxAutoShootingSeconds: 5.2,
    avgAutoFeedingSeconds: 1.9,
    avgAutoAttemptedSeconds: 3.8,
    autoShootingAccuracy: 0.7,
    avgTeleopShootingSeconds: 6.1,
    maxTeleopShootingSeconds: 8.5,
    teleopShootingAccuracy: 0.62,
    autoTrench: true,
    autoBump: false,
    autoFeed: false,
  },
  {
    team: 2056,
    matches: 8,
    avgShootingSeconds: 4.1,
    maxShootingSeconds: 6.3,
    avgFeedingSeconds: 2.5,
    trench: false,
    bump: false,
    halfFieldFromNeutral: true,
    halfFieldFromOpponent: false,
    fullField: false,
    L3Climbs: 2,
    L2Climbs: 4,
    L1Climbs: 2,
    autoClimbs: 1,
    avgAutoShootingSeconds: 2.3,
    maxAutoShootingSeconds: 3.5,
    avgAutoFeedingSeconds: 0.9,
    avgAutoAttemptedSeconds: 2.4,
    autoShootingAccuracy: 0.6,
    avgTeleopShootingSeconds: 4.6,
    maxTeleopShootingSeconds: 6.6,
    teleopShootingAccuracy: 0.55,
    autoTrench: false,
    autoBump: false,
    autoFeed: true,
  },
  {
    team: 1318,
    matches: 10,
    avgShootingSeconds: 4.9,
    maxShootingSeconds: 7.0,
    avgFeedingSeconds: 3.1,
    trench: true,
    bump: true,
    halfFieldFromNeutral: false,
    halfFieldFromOpponent: true,
    fullField: true,
    L3Climbs: 4,
    L2Climbs: 3,
    L1Climbs: 3,
    autoClimbs: 2,
    avgAutoShootingSeconds: 2.8,
    maxAutoShootingSeconds: 4.1,
    avgAutoFeedingSeconds: 1.2,
    avgAutoAttemptedSeconds: 2.9,
    autoShootingAccuracy: 0.65,
    avgTeleopShootingSeconds: 5.3,
    maxTeleopShootingSeconds: 7.2,
    teleopShootingAccuracy: 0.6,
    autoTrench: true,
    autoBump: true,
    autoFeed: true,
  },
];

export const SAMPLE_RED_ALLIANCE: MatchCardData[] = [
  SAMPLE_MATCH_CARD_DATA[0],
  SAMPLE_MATCH_CARD_DATA[1],
  SAMPLE_MATCH_CARD_DATA[2],
];

export const SAMPLE_BLUE_ALLIANCE: MatchCardData[] = [
  SAMPLE_MATCH_CARD_DATA[3],
  SAMPLE_MATCH_CARD_DATA[4],
  SAMPLE_MATCH_CARD_DATA[5],
];

export const SAMPLE_MATCH_CARD_BY_TEAM = new Map<number, MatchCardData>(
  SAMPLE_MATCH_CARD_DATA.map((team) => [team.team, team]),
);
